name: gitmoji
description: Gitmoji for Flutter
version: 3.13.0

homepage: https://github.com/cgutierr-zgz/gitmoji_flutter
repository: https://github.com/cgutierr-zgz/gitmoji_flutter
issue_tracker: https://github.com/cgutierr-zgz/gitmoji_flutter/issues

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.1.0
